<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_cmp_instructors',
		'title' => 'CMP Instructors',
		'fields' => array (
			array (
				'key' => 'field_544b7b35f7ded',
				'label' => 'Mobile / Phone',
				'name' => 'inst_mobile',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54cf4714142a5',
				'label' => 'Old Code',
				'name' => 'inst_old_code',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_544b819a99b78',
				'label' => 'Email',
				'name' => 'inst_email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_544b7b77f7dec',
				'label' => 'Specialization Category',
				'name' => 'inst_category',
				'type' => 'taxonomy',
				'taxonomy' => 'category',
				'field_type' => 'radio',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
				'required' => 1,
			),
				array (
				'key' => 'field_544baa35d7faf',
				'label' => 'Y.O.E',
				'name' => 'inst_experience',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '0.5',
				'max' => '',
				'step' => '0.5',
			),
				array (
				'key' => 'field_544baa35d7theid',
				'label' => 'Unique ID',
				'name' => 'inst_id',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_544baa740ff2a',
				'label' => 'Education',
				'name' => 'inst_education',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_544baa9f0ff2a',
				'label' => 'Comments/Notes',
				'name' => 'inst_comments',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'instructor',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
?>